trigger: none

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: joseph-flinn
    userRepository: joseph-flinn/desktop
  displayName: 'git release artifacts'

- script: ls -alh $(System.ArtifactsDirectory)
  displayName: 'show artifacts'

- script: |
    echo 'Signing artifacts'
  displayName: 'sign artifacts'

- script: |
    echo 'Publishing artifacts'
  displayName: 'publish artifacts'
