trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: code-signing-test

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global azuresigntool'
  displayName: 'install AzureSignTool'

- script: azuresigntool sign --help
  displayName: 'Debugging AST'

- task: DownloadGitHubRelease@0
  inputs:
    connection: joseph-flinn
    userRepository: joseph-flinn/desktop
  displayName: 'git release artifacts'

- bash: |
    GIT_RELEASE_VERSION=$(curl --silent "https://api.github.com/repos/joseph-flinn/desktop/releases/latest" | awk -F '"' '/tag_name/{print $4}' | awk '{print substr($1, 2); }') 
    echo "##vso[task.setvariable variable=git_release_version]$GIT_RELEASE_VERSION"
  displayName: 'set git_release_version'

- script: |
    ls -alh $(System.ArtifactsDirectory)
    echo GIT_RELEASE_VERSION=$(git_release_version)
  displayName: 'show artifacts'

- script: |
    azuresigntool sign ^
    -kvu "$(SigningVaultURL)" ^
    -kvi "$(SigningClientId)" ^
    -kvs "$(SigningClientSecret)" ^
    -kvt "$(SigningTenantId)" ^
    -kvc "$(SigningCertName)" ^
    -v ^
    -ifl ^
    "$(System.ArtifactsDirectory)\Bitwarden-$(git_release_version)-ia32.appx" ^
    "$(System.ArtifactsDirectory)\Bitwarden-$(git_release_version)-x64.appx"
  displayName: 'Sign artifacts'

- task: PublishPipelineArtifact@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/dist/Bitwarden-$(git_release_version)-ia32.appx'
    artifactName: 'Bitwarden-$(git_release_version)-ia32.appx'

- task: PublishPipelineArtifact@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/dist/Bitwarden-$(git_release_version)-x64.appx'
    artifactName: 'Bitwarden-$(git_release_version)-x64.appx'
