trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: code-signing-test

steps:
- script: |
    git clone https://github.com/vcsjones/AzureSignTool.git
    dotnet tool restore

    #set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    #dotnet tool install --global AzureSignTool --version 2.0.17
  displayName: 'install AzureSignTool'

- script: dotnet tool list
  displayName: 'testing dotnet tool list'

- script: AzureSignTool.exe sign --help
  displayName: 'Debugging AST'

