trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: code-signing-test

steps:
- script: |
    git clone https://github.com/vcsjones/AzureSignTool.git
    cd AzureSignTool/src/AzureSignTool
    dotnet tool restore
  displayName: 'install AzureSignTool'

- script: dotnet tool list
  displayName: 'testing dotnet tool list'

- script: AzureSignTool.exe sign --help
  displayName: 'Debugging AST'

