# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: code-signing-test

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: PowerShell@2 
  inputs:
    targetType: 'inline'
    script: | 
      $packageVersion = (Get-Content -Raw -Path $(System.DefaultWorkingDirectory)\src\package.json | ConvertFrom-Json).version;
      echo "##vso[task.setvariable variable=PACKAGE_VERSION]${packageVersion}"
  displayName: 'Setting packageVersion'

- script: |
    echo "package version: ${ PACKAGEVERSION }"
    echo "package version: $(PACKAGEVERSION)"
    exit 1 
  displayName: Package Version testing

- script: npm install
  displayName: 'npm install'

- script: |
    npm run build
    npm npm run clean:dist
  displayName: 'npm build'

# This task is not working...
- script: npx electron-builder --win --x64 --ia32 -p never -c.win.certificateSubjectName=\"Bitwarden Inc\"
  displayName: 'electron-builder build & sign'
  env:
    CSC_LINK: $(ebSigningCertIdentifierURL)
    CSC_KEY_PASSWORD: $(ebSigningCertKey)

- script: ls -alht dist
  displayName: show executables

- script: ls -alht dist/nsis-web
  displayName: show nsis-web executables

- task: PublishPipelineArtifact@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/dist/Bitwarden-Portable-${ packageVersion }.exe'
    artifactName: Bitwarden-Portable-$(packageVersion).exe

# - task: PublishPipelineArtifact@1
#   inputs:
#     pathToPublish: '$(System.DefaultWorkingDirectory)/dist/Bitwarden-1.23.1-ia32.appx'
#     artifactName: Bitwarden-$(GIT_COMMIT_TO_BUILD)-ia32.appx
# 
# - task: PublishPipelineArtifact@1
#   inputs:
#     pathToPublish: '$(System.DefaultWorkingDirectory)/dist/Bitwarden-1.23.1-x64.appx'
#     artifactName: Bitwarden-$(GIT_COMMIT_TO_BUILD)-x64.appx
