name: Deploy

on: 
  release:
    types:
      - prereleased

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: testing
        run: |
          echo ${{ github.ref }}
          echo ${{ github.event.GITHUB_REF }}

