name: Windows Environment Exploration

on:
  workflow_dispatch:

jobs:
  exp:
    runs-on: windows-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Set Node options
        run: echo "NODE_OPTIONS=--max_old_space_size=4096" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Install & Test pkg
        run: |
          npm install -g pkg
          pkg --help

      - name: Download RH
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri http://www.angusj.com/resourcehacker/resource_hacker.zip -OutFile "resource_hacker.zip"
          Expand-Archive -Path resource_hacker.zip -DestinationPath resource_hacker

      - name: List RH
        run: dir resource_hacker

      - name: Get Current Directory
        shell: pwsh
        run: Get-Location

      - name: Debugging Path
        shell: pwsh
        run: |
          echo "D:\a\cli\cli\resource_hacker" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo $env:GITHUB_PATH

      - name: ResourceHacker Test
        shell: pwsh
        run: |
          $args = "-help"
          start-process -filepath "ResourceHacker.exe" -argumentlist $args


      - name: ResourceHacker Test
        run: |
          cd resource_hacker
          dir
          ResoureHacker.exe -help
